name: unsupport-project-bom

on:
  push:
    branches: [main]

jobs:
  unsupport-python-project-with-bom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Unsupport a Python project with BoM
        #--> Run the GitHub action
        uses: codenotary/vcn-unsupport-bom-python-github-action@v1.0.0
        # uses: codenotary/vcn-unsupport-bom-python-github-action@main
        with:
          asset: git://.
          cnil_host: ${{ secrets.CNIL_HOST }}
          cnil_grpc_port: ${{ secrets.CNIL_GRPC_PORT }}
          cnil_api_key: ${{ secrets.CNIL_API_KEY }}
        #<--
        #--> or run the vcn Docker image directly (all vcn flags are available and passed through)
        # for Python 2:
        # uses: docker://codenotary/vcn:bom-python2
        # for Python 3:
        # uses: docker://codenotary/vcn:bom-python3
        # with:
        #   args: a git://. --lc-host ${{ secrets.CNIL_HOST }} --lc-port ${{ secrets.CNIL_GRPC_PORT }} --lc-api-key ${{ secrets.CNIL_API_KEY }} --signerID ${{ github.event.sender.login }}@github --bom
        #<--
